name: basic-node - Basic Build Action

on:
  push:
    branches:
      - main
    paths:
      - examples/apps/basic-node/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      working-directory: examples/apps/basic-node
      run: |
        npm install
    - name: build docker image
      run: |
        docker build -t basic-node .
