name: basic-node - Basic Build Action

on:
  push:
    branches:
      - main
    paths:
      - examples/apps/basic-node/**
  pull_request:
    branches: 
      - main
    paths:
      - examples/apps/basic-node/**


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Ubuntu Server 
      run: |
        apt update
        apt install -y wget git curl p7zip-full ca-certificates qpdf ghostscript

    - name: Download qualysapi from Github and executing- Kudos to VIA team!
      env: 
        QUALYS_LAUNCH_MODE=2
        QUALYS_SCANNER_TYPE=${{VARI}}
        QUALYS_URL=${{vars. QUALYS_URL}}
        QUALYS_USER=${{secrets.QUALYS_USER}}
        QUALYS_USER_PASS=${{secrets.QUALYS_USER_PASS}}
        QUALYS_PROJECT_NAME=${{vars.QUALYS_PROJECT_NAME}}
        QUALYS_WEBAPP_ID=${{vars.QUALYS_WEBAPP_ID}}
        QUALYS_OPTION_PROFILE_ID='${{vars.QUALYS_OPTION_PROFILE_ID}}
        QUALYS_SEND_REPORT=${{vars.QUALYS_SEND_REPORT}}
        QUALYS_ENCRYPT_REPORT=${{vars.QUALYS_ENCRYPT_REPORT}}
        QUALYS_ENCRYPT_PASS=${{secrets.QUALYS_ENCRYPT_PASS}}
        QUALYS_REPORT_RECEIVERS=${{vars.QUALYS_REPORT_RECEIVERS}}
      run: |
        git clone https://github.com/0xtiago/qualysapi

    - name: npm install
      working-directory: examples/apps/basic-node
      run: |
        npm install
    - name: build docker image
      working-directory: examples/apps/basic-node
      run: |
        docker build -t basic-node .
